                    "      ¸oO   " \
                    "    ¸oO@O   " \
                    "   ¸oO@@o   " \
                    "  .oO@@Oº   " \
                    "   °ºO@O    " \
                    "    °O@O    " \
                    "    °o@O    " \
                    "    •o@O    " \
                    "    •o@O    " \
                    "    .O@O    " \
                    "    .O@O    " \
                    "   ¸oO@Oo   " \
                    "  .oOO@@OO  " \
                    "  °ºOOOOOº  " \
