#!/bin/bash
#----------------------------------------------------------------------#
# FILE:    more_funx                                                   #
# AUTHOR:  Douglas Roberts -- droberts                                 #
# CREATED: Fri Jan 13 15:17:01 GMT 2017                                #
# PURPOSE: soooo many useful functions.... just trying to manage       #
#          the chaos... keep the gobbledy-gook syntax away from        #
#          the primary script.                                         #
#----------------------------------------------------------------------#

check=$( which quickread.exe )
if [[ -z $check ]]; then
    cat << EOF | xargs -I {} echo "[38;5;15;48;5;93m" {} "[m"

"quickread.exe" is not in your path.
you must:

cc pause.c -o pause.exe
cd SOME_LOCAL_DIRECTORY_IN_YOUR_PATH
mv $OLDPWD/pause.exe .
ln pause.exe quickread.exe

otherwise, you will have to replace all references
to stock_read, stock_quickread.exe, quickread.exe and pause.exe
to a simple "read" method and
remove any references to descriptions.

much easier to just compile pause.exe...

EOF
    exit
fi



set -o allexport
DEBUG=1
color_idx=-1
DEBUG=0
DLOG=$HOME/d.log
declare -a _fgs
shopt -s expand_aliases

# greens to blues to purples
declare -a cool_cat_fgs
# default
cool_cat_fgs=(
     40  41  43  44
     45  80 117 153
    147 141 135 129
     93  57  21  33
     39  38 37
    )
cool_cat_idx=0

#----------------------------------------------------------------------#
# bash implementation of the C macros: __FILE__ __LINE__               #
# must be used:                                                        #
# eval $__line__                                                       #
#----------------------------------------------------------------------#
__line__='eval echo "[32m $BASH_SOURCE [33m $FUNCNAME [35m $LINENO: [m"'



function is_file
{
test -f $1
}

function is_dir
{
test -d $1
}


function grab_state
{
eval $( cat $FSTATE /dev/null )
}


function show_state
{
if [[ -z $FSTATE ]]; then
    printc red no FSTATE file specified
    pause
    return
fi

if [[ ! -f $FSTATE ]]; then
    echo '[31m' `/bin/ls -ld $FSTATE` '[m'
    pause
    return
fi

cat $FSTATE
pause
return
}


function unsetxv
{
case $- in
    (*x*v*|*v*x*)
        set_xv=1
        set +xv
        ;;
    (*) set_xv=0 ;;
esac
}


function setxv
{
if [[ $set_xv -eq 1 ]]; then
    set -xv
fi
}


function resize
{
vecho lines
vecho columns
}


function cool_cat
{
# grabs random color-idx. considers environ light/dark setting.
local r g b idx _gg
DEF_IFS="${IFS}"
IFS='' # retains input spaces
while read line ; do
    incr cool_cat_idx
    if [[ $cool_cat_idx -ge $pound_cool_cat_fgs ]]; then
        cool_cat_idx=0
    fi
    idx=${cool_cat_fgs[cool_cat_idx]}

#     case ${_g:-38} in
#         48)
#             _gg=38
# #             (( r = RANDOM % 3 ))
# #             (( g = RANDOM % 3 ))
# #             (( b = RANDOM % 3 ))
#             ;;

#         38)
#             _gg=48
# #             (( r = ( RANDOM % 3 ) + 3 ))
# #             (( g = ( RANDOM % 3 ) + 3 ))
# #             (( b = ( RANDOM % 3 ) + 3 ))
#             ;;

#         *) echo "$line" ; continue ;;
#     esac

    # (( idx = 16 + b + (g*6) + (r*36) ))
    # echo "[m${idx} [${_gg};5;${idx}m${line}[m"
    echo "[${_g};5;${idx}m${line}[m"
    # echo "[${_g};5;${idx}m${line}[m"
done
echo -n '[m'
# return to default values
IFS="${DEF_IFS}"
return
}


function fig
{
_goop=$( echo "$*" | sed -e 's/[^A-Za-z][^A-Za-z]*/.*/g' )
find . -type f -exec grep -i "$_goop" {} \; -print
}


function goopy
{
_goop=$( echo "$*" | sed -e 's/[^A-Za-z][^A-Za-z]*/.*/g' )
grep -i "$_goop" *.py
}


#----------------------------------------------------------------------#
# meh. syntax improvement for counters.                                #
#----------------------------------------------------------------------#
function init
{
eval ${1:-num}=${2:-0}
}


#----------------------------------------------------------------------#
# report status in color!                                              #
#----------------------------------------------------------------------#
function report_status
{
if [[ $? -eq 0 ]]; then
    echo 💚 PASSED $*
else
    echo 🔴 FAILED $*
fi
return
}


function exec_vi
{
local FIN
local finput
local vi_opt
local _x

#----------------------------------------------------------------------#
# perhaps called with nothing...                                       #
#----------------------------------------------------------------------#
if [[ -z $1 ]]; then
    return
fi

case $# in
    (0) echo called with nothing ; return ;;
    (1) finput=$1 ;;
    (2) _x=${1#+}
        _x=${1#/}
        _x=$( grepify "${_x}" )
        case $_x in
            ([0-9]*) vi_opt="+${_x}" ;;
            (*) vi_opt="+/${_x}" ;;
        esac
        finput=$2
        ;;
    (*) echo no idea what you are trying to do with $* ; return ;;
esac

#----------------------------------------------------------------------#
# if not a good path, is it an executable?                             #
#----------------------------------------------------------------------#
for FIN in $finput `which $finput`; do
    if [[ -z $FIN ]]; then
        continue
    fi
    if [[ ! -f $FIN ]]; then
        continue
    fi
    ftype=$( file $FIN | cut -d: -f2 )
    case $ftype in
        (*Mac*executable*) continue ;;
        (directory) continue ;;
    esac
    # necessary. otherwise the blank vi_opt shows up as a file in vi
    # :-P
    if [[ -n $vi_opt ]]; then
        exec /usr/bin/vi $vi_opt $FIN
    else
        exec /usr/bin/vi $FIN
    fi
done
return
}


function pause
{
stty erase 
echo -n "Press <RETURN> to continue "
read nothing
return
quickread.exe
}


#----------------------------------------------------------------------#
# forever prompting for stuff... genericize!                           #
# next up: generic menues!                                             #
#----------------------------------------------------------------------#
function stock_read
{
unsetxv
if [[ -z $1 ]]; then
    echo no variable name specified
    pause
    return 1
fi

#----------------------------------------------------------------------#
# local variables, similar to possible input. use underscores here.    #
#----------------------------------------------------------------------#
local _var_name=$1
local _answer
local _prompt
local _value
shift

#----------------------------------------------------------------------#
# use provided text for prompt, if any. else show var-name.            #
#----------------------------------------------------------------------#
_prompt="Enter value for ${_var_name//_/-}:"
# if [[ -n $* ]]; then
#     _prompt="$*:"
# else
#     _prompt="Enter value for ${_var_name//_/-}:"
# fi

#----------------------------------------------------------------------#
# extract current value of input variable name                         #
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - #
# eval _value=\"\$${_var_name}\"                                       #
#----------------------------------------------------------------------#
_value=${!_var_name}

#----------------------------------------------------------------------#
# if we only need a single character, we should use "quickread.exe"    #
#----------------------------------------------------------------------#
if [[ $_use_quick -eq 1 ]]; then
    _use_quick=0

#----------------------------------------------------------------------#
# grab the value                                                       #
#----------------------------------------------------------------------#
    echo current value of $_var_name is $_value
    echo -n "$_prompt "
    _answer=$( quickread.exe )
    echo $_answer
    eval $_var_name=\""${_answer}"\"
    return
fi

#----------------------------------------------------------------------#
# looking for a string input. show user current value, if set.         #
#----------------------------------------------------------------------#
if [[ -n $_value ]]; then
    echo "current value for: |${_var_name//_/-}| is |$_value|"
    echo "hit <ENTER> to retain. hit 'c' to clear."
fi

#----------------------------------------------------------------------#
# problem with MacOS and tty settings fix...?                          #
# this was caused by the default setting in Terminal.App,              #
# where in the Advanced-tab, the "delete key sends CONTROL-H"          #
# checkbox is unchecked.                                               #
# pretty sure this does nothing, but left here for future issues.      #
#----------------------------------------------------------------------#
stty erase 

#----------------------------------------------------------------------#
# grab the value                                                       #
#----------------------------------------------------------------------#
echo -n "$_prompt "

#----------------------------------------------------------------------#
# ... and finally, get the input from the user and prosper.            #
#----------------------------------------------------------------------#
read _answer

#----------------------------------------------------------------------#
# retain previous value, if given nothing.                             #
#----------------------------------------------------------------------#
if [[ -z $_answer ]]; then
    stderr retaining: $_var_name =\> $_value
    return
fi

#----------------------------------------------------------------------#
# clear! too bad if you need c as a value. moo ah ha ha!               #
# (probly should use stock_quickread in that case. )                   #
#----------------------------------------------------------------------#
case $_answer in
    (c) _answer= ;;
esac

#----------------------------------------------------------------------#
# strip double quotes from paste.                                      #
# (very, very clever hack for quote checking.)                         #
#----------------------------------------------------------------------#
_answer=$( echo "$_answer" | tr \"\" .. )

#----------------------------------------------------------------------#
# set the variable value.                                              #
#----------------------------------------------------------------------#
eval $_var_name=\"$_answer\"

setxv
return
}


#----------------------------------------------------------------------#
# stock variable quickread-ing, accounting for previous settings.      #
#----------------------------------------------------------------------#
function stock_quickread
{
_use_quick=1
stock_read $*
vecho $1
}


function countdown
{
local seconds
seconds=${1:-10}
echo counting down $seconds ... .. .
while [[ $seconds -gt 0 ]]; do
    echo -ne "\b\b\b\b$seconds "
    decr seconds
    sleep 1
done
echo -e '\b\b\b\b0 '
echo done
return
}


#----------------------------------------------------------------------#
# tired of writing this one out, too...                                #
#----------------------------------------------------------------------#
function status
{
if [[ $? -eq 0 ]]; then
    return 0
fi
return 1
}


#----------------------------------------------------------------------#
# random color index.                                                  #
#----------------------------------------------------------------------#
function start_color_idx
{
debug
_fgs=( $( grep ^color-idx: ~/.ccat.log | cut -d: -f2 ) )
color_idx=0
}


function incr_color
{
debug
if [[ $color_idx -eq -1 ]]; then
    start_color_idx
    color_idx=0
    return
fi
#----------------------------------------------------------------------#
# set initial color index. I suppose I could decrement also...?        #
#----------------------------------------------------------------------#
(( color_idx += 1 ))
if [[ $color_idx -ge ${#_fgs[*]} ]]; then
    color_idx=0
fi
}


#----------------------------------------------------------------------#
# log a message. honest. not a wrapper to a log. not an interface.     #
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - #
#       echo 🔵 INFO                                                   #
#       echo 💚 PASS                                                   #
#       echo 🔴 FAIL                                                   #
#       echo 💜 INFO-2                                                 #
#----------------------------------------------------------------------#
function log_msg
{
case $1 in
    info|INFO)   echo -n "🔵 " ; shift ;;
    pass|PASS)   echo -n "💚 " ; shift ;;
    fail|FAIL)   echo -n "🔴 " ; shift ;;
    info2|INFO2) echo -n "💜 " ; shift ;;
esac
echo $* | tee -a ${FLOG:-/dev/stdout}
return
}


#----------------------------------------------------------------------#
# very tired of typing this particular sequence.                       #
#----------------------------------------------------------------------#
function zero
{
zero=${1:-${0:-default}}
zero=${zero##*/}
zero=${zero%.sh}
zero=${zero%.py}
export zero
#----------------------------------------------------------------------#
# echo "zero=${zero}" > ~/.state/more_funx.state                       #
#----------------------------------------------------------------------#
}

#----------------------------------------------------------------------#
# increments the variable named in 1, by the amount in 2, if present.  #
# otherwise, just adds 1.                                              #
#----------------------------------------------------------------------#
function incr
{
eval "(( ${1:-num} += ${2:-1} ))"
}
function decr
{
eval "(( ${1:-num} -= ${2:-1} ))"
}


#----------------------------------------------------------------------#
# output something right into my global buffer.                        #
#----------------------------------------------------------------------#
function teed
{
tee ~/:-D
}

#----------------------------------------------------------------------#
# standardized results printing.                                       #
#----------------------------------------------------------------------#
function passed
{
printc -n green,black PASSED:; echo -n " "
}

function failed
{
printc -n red,yellow2 FAILED:; echo -n " "
}


#----------------------------------------------------------------------#
# nicer array and associative-array declaration syntax.                #
# although... neither is technically necessary, as you can simply      #
# just start assigning values...                                       #
#----------------------------------------------------------------------#
function array
{
eval declare -a ${1:-safety_net}
}

function aarray
{
eval declare -A ${1:-safety_net}
}


#----------------------------------------------------------------------#
# show me the current log                                              #
#----------------------------------------------------------------------#
function flog
{
METHOD=${1:-${METHOD:-safety-net}}
#----------------------------------------------------------------------#
# grab latest log based on numeric log number.                         #
#----------------------------------------------------------------------#
export flog
flog=$(
    /bin/ls -t ${LOGDIR}/$METHOD.log* $METHOD.log* 2>/dev/null |
        awk -F. '{print $NF, $0}' |
        sort -rn |
        head -1 |
        fields 2
    )
echo $flog
return
}


#----------------------------------------------------------------------#
# sends stderr to null.                                                #
#----------------------------------------------------------------------#
function shunt
{
$* 2>/dev/null
}


#----------------------------------------------------------------------#
# takes the source-file-name and returns the CamelCase value.          #
#----------------------------------------------------------------------#
function camel
{
export camel=$( python -c "print('$*'.title().replace('_',''))" )
}


#----------------------------------------------------------------------#
# put something in background inconspicuously.                         #
#----------------------------------------------------------------------#
uber_bg()
{
( eval $* & ) > /dev/null 2>&1
return
}


#----------------------------------------------------------------------#
# writes stdout to stderr.                                             #
#----------------------------------------------------------------------#
function stderr
{
echo "$@" 1>&2
}


function debug
{
#----------------------------------------------------------------------#
# turn off debugging upon entry                                        #
#----------------------------------------------------------------------#
set +xv

#----------------------------------------------------------------------#
# set the environ DEBUG=on or DEBUG=1 or DEBUG=color                   #
# to turn on noisy shell execution.                                    #
#----------------------------------------------------------------------#
case ${DEBUG:-off} in

    (on|1)
        CLEAR=
        PS4='+ FILE: $BASH_SOURCE FUNCTION: $FUNCNAME LINE: ${LINENO}: '
        set -xv
        ;;

    (color)
        CLEAR=
        PS4='\
\[\e[36m\]\
\[\e[3m\]+PS4 \
\[\e[32m\]FILE: \
\[\e[35m\]${BASH_SOURCE##*/} \
\[\e[32m\]FUNCTION: \
\[\e[35m\]${FUNCTION:-main-shell} \
\[\e[32m\]LINE: \
\[\e[35m\]${LINENO} \
\[\e[0m\] '
        set -xv
        ;;

    (off|0)
        set +xv
        # PS4='PS4 -> '
        ;;

esac
}


#----------------------------------------------------------------------#
# execute arguments if in debug mode.                                  #
#----------------------------------------------------------------------#
function ex_debug
{
if [[ ${DEBUG:-0} -eq 1 ]]; then
    eval $*
fi
}


function random_color
{
local shade idx r g b offset
export _color

shade=${1:-light}

case $shade in
    dark)
        offset=0
        ;;
    *)
        offset=3
        ;;
esac

(( idx = ( RANDOM % 3 ) + offset ))
(( r = 36 * idx ))

(( idx = ( RANDOM % 3 ) + offset ))
(( g = 6 * idx ))

(( b = ( RANDOM % 3 ) + offset ))


(( _color = r + g + b + 16 ))

echo $_color
}


function print_highlight
{
local which_way fg bg args
(( which_way = RANDOM % 2 ))

args=
if [[ $1 = -* ]]; then
   args=$1
   shift
fi

case $which_way in
    0)
        _bg=$( random_color dark )
        _fg=$( random_color light )
        ;;
    *)
        _fg=$( random_color dark )
        _bg=$( random_color light )
        ;;
esac

printc $_bg,$_fg $*
# echo $args "[48;5;${_bg}m[38;5;${_fg}m${*}[m"
}


#----------------------------------------------------------------------#
# test_highlight                                                       #
#----------------------------------------------------------------------#
function test_highlight
{
for y in 1 2 3 ; do
for x in 1 2 3 4 5 6 7 8 9 10 11 12 ; do
    print_highlight `date; date`
    print_highlight -n `date` ; date
done
done
}


#----------------------------------------------------------------------#
# aurghle that MacOS shell does not support ${var,,} and ${var^^}      #
# nor: typeset -L or typeset -U                                        #
# it is a travesty that we have to fork, not 1, but 2 processes        #
# to overcome this deficiency in MacOS shell support.                  #
#----------------------------------------------------------------------#
function lower
{
local __x
eval __x=\$$1

local __y
__y=$( echo $__x | tr '[:upper:]' '[:lower:]' )
eval ${1}=$__y
}


function upper
{
local __x
eval __x=\$$1

local __y
__y=$( echo $__x | tr '[:lower:]' '[:upper:]' )
eval ${1}=$__y
}


function display_boilerplate_options
{
echo "    (x) vi this script and exec"
echo "    (@) vi @ buffer"
echo "    (m) git.menu"
echo "    (n) notes"
echo "    (u) urls"
echo "    (y) yoga-schedule"
echo "    (r) return"
echo "    (t) timmy"
echo "    (q) quit"
echo "    (=) quit"
echo "    (/) help"
echo "    (!) bash"
return
}


#----------------------------------------------------------------------#
# boilerplate menu options method.                                     #
#----------------------------------------------------------------------#
function boilerplate
{
debug
case $* in
#----------------------------------------------------------------------#
# store something in the memory buffer real quick.                     #
#----------------------------------------------------------------------#
    (@) vi ~/Dropbox/:-D ;;

    (t) stock_read input_for_timmy
        timmy $input_for_timmy
        pause
        ;;

#----------------------------------------------------------------------#
# edit and continue. which in order to follow links.                   #
# if this screws up, cd somewhere else. and restart.                   #
#----------------------------------------------------------------------#
    (x) cd ; FIN=$( which ${0##*/} )
        vi $FIN ; exec $FIN ;;

   (blibbity)
        if [[ $0 == ./* ]]; then
            if [[ -f $0 ]]; then
                FIN=$0
            else
                # probably chdir-ed in the script.
                FIN=$( cd ; which $0 )
            fi
        else
            FIN=$( cd ; which $0 )
        fi
        vi $FIN ; exec $FIN
        ;;

#----------------------------------------------------------------------#
# omnipresent options.                                                 #
#----------------------------------------------------------------------#
    (n) notes ${TOPIC:-${zero}} ;;
    (u) urls ${TOPIC:-${zero}} ;;
    (D) # toggle debug node
        case ${DEBUG:-1} in
            (1) DEBUG=0 ; echo debug is on ; pause ;;
            (*) DEBUG=1 ; echo debug is off ; pause ;;
        esac
        ;;

    (y) yoga ;;
    (r) return ;;
    (q|=) # exit
        echo ; echo complete ; echo ; exit 0 ;;
    (!) bash ;;
    (/) display_boilerplate_options
        pause
        ;;
    (*) # invalid option
        err="\
[31m[3mInvalid selection: $answer[m"
       ;;

esac
return
}


#----------------------------------------------------------------------#
# for shell scripts working as pipes or parameters.                    #
# this will be real valuable and sleek eventually.                     #
#----------------------------------------------------------------------#
function boilerplate_shargs
{
cat ~/Dropbox/bin/boilerplate_shargs.template
}


#----------------------------------------------------------------------#
# random selection from stdin.                                         #
#----------------------------------------------------------------------#
function random_selection
{
while read line ; do
    echo $RANDOM $line
done | sort -run | head -1 | cut -d' ' -f2-
}

#----------------------------------------------------------------------#
# returns bright random ANSI standard color index.                     #
#----------------------------------------------------------------------#
function random_color_simple
{
(( color_idx = (RANDOM % ((6*6*6)-2)) + 18 ))
}


#----------------------------------------------------------------------#
# abrupt ending to JIC.                                                #
#----------------------------------------------------------------------#
function noimp
{
echo not-implemented
exit
}

RB_fgs=(
     46  47  48  49  50
     51  45  39  33  27
     21  57  93 129 165
    201 200 199 198 197
    196 202 208 214 220
    226 190 154 118  82
    )

function rainbow_me
{
#----------------------------------------------------------------------#
# DEBUG=color                                                          #
#----------------------------------------------------------------------#
#----------------------------------------------------------------------#
# debug                                                                #
#----------------------------------------------------------------------#
local x fg
for x in x x ; do
for fg in ${RB_fgs[*]}; do
    echo -n "[48;5;${fg}m" # bg only
    echo -n "[38;5;${fg}m•" # fg only
#----------------------------------------------------------------------#
#     echo -n "[48;5;${fg};38;5;${fg}m•" # both                     #
#----------------------------------------------------------------------#
done
done
echo "[m"
}


function reset_ansi
{
echo -n "[m"
}


#----------------------------------------------------------------------#
# this function takes the place of this awful bash syntax:             #
# ${#var[*]} to mean "how many elements in this array?"                #
#----------------------------------------------------------------------#
function pound
{
local _nothing
local var=${1:-_nothing}
eval pound_${var:-_nothing}=\${\#${var}'[*]}'
}

#----------------------------------------------------------------------#
# create a variable named <INPUT-VARIABLE-NAME>_pound                  #
# whose value is the number of elements in the parameter variable.     #
# this is to avoid the nasty syntax shown below.                       #
# so . . . the use case is this. say you have a bash array:            #
#                                                                      #
# % ant=( bat cat dog emu )                                            #
#                                                                      #
# the number of elements in $ant is 4; which can be accessed via:      #
#                                                                      #
# % echo ${#ant[*]}                                                    #
#   4                                                                  #
#                                                                      #
# ... which is definitively the worst syntax in the history            #
#    of programming.                                                   #
#                                                                      #
# this method changes that to:                                         #
#                                                                      #
# % create_pound ant                                                   #
#                                                                      #
# ... and creates the variable:                                        #
#                                                                      #
# % echo $ant_pound                                                    #
#   4                                                                  #
#                                                                      #
#----------------------------------------------------------------------#
function create_pound
{
local _x=$1
eval ${1}_pound='${#'${_x}'[*]}'
}


function same
{
$* 2>&1
}

function devnull
{
$* > /dev/null 2>&1
}

function shunt
{
$* 2>/dev/null
}

#----------------------------------------------------------------------#
# show the value of a variable, bypassing the dollar braces syntax.    #
#----------------------------------------------------------------------#
function vecho
{
local _upper;
local _lower;
local _x;
#----------------------------------------------------------------------#
# create upper and lower case versions of the variable name input,     #
# also converting hyphens to underscores, in order to keep the         #
# user from having to hit the shift key.                               #
#----------------------------------------------------------------------#
_x=${1:-PATH}
_lower=$( echo $1 | /usr/bin/tr '[:upper:]-' '[:lower:]_' );
_upper=$( echo $1 | /usr/bin/tr '[:lower:]-' '[:upper:]_' );

#----------------------------------------------------------------------#
# just print the value.                                                #
#----------------------------------------------------------------------#
#----------------------------------------------------------------------#
# eval echo \${_x:-\${${_upper}:-\${${_lower}}}};                      #
# return                                                               #
#----------------------------------------------------------------------#

#----------------------------------------------------------------------#
# make it look like a declaration.                                     #
#----------------------------------------------------------------------#
eval echo ${_x} ==\\\> \${$_x:-\${${_upper}:-\${${_lower}}}};
return
}


function vacho
{
if [[ $# -eq 2 ]]; then
    shift
    echo -n "${1}=( "
    eval echo -n ${1}='( ${'$1'[*]} )'
else
    eval echo -n '${'$1'[*]}'
fi
echo
return
}


# this version supports changing hyphens to underscores
# and also trying both lower and upper case variables
# it does as much and more as the version above,
# but with amazingly less syntactic noise.
# does not work with MacOS because of the ^^
# hence, that monstrosity above.
function LINUXvecho
{ 
local name
name=${1/-/_}
eval value=\$$name
if [[ -z $value ]]; then
    name=${name^^}
    eval value=\$$name
fi
echo $name=$value
}


function echopath
{
vecho ${1:-PATH} |
  /usr/bin/tr '=: ' '\012\012\012' |
  grep . |
  nl -ba |
  more -E
}


function debug_pause
{
if [[ $DEBUG -eq 0 ]]; then
    return
fi

echo -n "[33mdebug-pause:[m continue? y/n "
answer=$( quickread.exe )
echo
echo $answer
case $answer in
    y) return ;;
    *) echo quitting . . . ; exit 4 ;;
esac
}

function pirate
{
echo "[38;5;200m[48;5;92m${*}[m"
}

function teelog
{
echo "$*" | tee -a $FLOG
}

#----------------------------------------------------------------------#
# very useful, so just call if given the parameter.                    #
#----------------------------------------------------------------------#
if [[ -n $1 ]]; then
    zero $1
    FTMP=/tmp/$zero.$LOGNAME
    FSTATE=$HOME/.pogo/$zero.pogo
    touch $FSTATE
#----------------------------------------------------------------------#
#     . $FSTATE   sorry do not feel like debugging every single script i ever wrote #
#----------------------------------------------------------------------#
    FOUT=./$zero.out
    FLOG=$DLOG/$zero.log
    TOPIC=$zero
fi

# nece
pound cool_cat_fgs

