#!/bin/bash
#----------------------------------------------------------------------#
# FILE:    yaps1                                                       #
# AUTHOR:  Douglas Roberts -- droberts                                 #
# CREATED: Tue Feb 12 10:16:20 EST 2019                                #
# PURPOSE: yet another prompt setting script.                          #
#          cycle through list of background colors.                    #
#----------------------------------------------------------------------#
set -o allexport

#----------------------------------------------------------------------#
# initialize state, only if not done yet.                              #
#----------------------------------------------------------------------#
FPS1=~/.state/.yaps1
declare -a palettes
if [[ ! -f $FPS1 ]]; then
    echo _idx=0 > $FPS1 2>/dev/null
fi

#----------------------------------------------------------------------#
# TODO: avoid staircase effect                                         #
# TODO: toggle background / foreground color change.                   #
#----------------------------------------------------------------------#

#----------------------------------------------------------------------#
# yikes. a duplicate of the function in more_funx.                     #
# but these 2 scripts must remain independent to avoid                 #
# recursive sourcing mistakes.                                         #
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - #
# this function takes the place of this awful bash syntax:             #
# ${#var[*]} to mean "how many elements in this array?"                #
#----------------------------------------------------------------------#
function pound
{
local _nothing
local var=${1:-_nothing}
eval pound_${var:-_nothing}=\${\#${var}'[*]}'
}


#----------------------------------------------------------------------#
# BEGIN COLOR PALETTE SETTINGS FUNCTIONS.                              #
#----------------------------------------------------------------------#

#----------------------------------------------------------------------#
# set the upper bound which is dynamic based on colors list            #
#----------------------------------------------------------------------#
function _yap_pound
{
pound acidx
#----------------------------------------------------------------------#
# vecho pound_acidx                                                    #
#----------------------------------------------------------------------#
return
}


function yap_pastels4 # colors
{
#----------------------------------------------------------------------#
#      50  86 122 158 81 117 159 123  87  51 45  81                    #
#----------------------------------------------------------------------#
#----------------------------------------------------------------------#
#     159 123 87 51 50 86 122 158 121 85 49                            #
#----------------------------------------------------------------------#
acidx=(
    159 123 87 51 50 86 122 158 121 85 49
    )
_yap_pound ; palette=$FUNCNAME ; _idx=0
}


function barb # colors
{
acidx=( 163 164 165 165 171 177 213 207 201 200 199 205 206 170 169 )
### too dark:
acidx=( 231 225 219 213 207 201 200 199 198 197 196 160 124 88 )
acidx=( 231 225 219 213 207 207 201 200 199 198 197 196 160 124 )
_yap_pound ; palette=$FUNCNAME ; _idx=0
}

#----------------------------------------------------------------------#
# pastel rainbow.                                                      #
#----------------------------------------------------------------------#
alias yap_rainbow_light=yap_rainbow
alias yap_rainbow_pastel=yap_rainbow


function yap_bmw # colors
# blue-magenta-white
{
acidx=( 225 219 213 207 201 165 129  93  57  21  20  19  18  17 )
_yap_pound ; palette=bmw ; _idx=0
}



function yap_rainbow # colors
{
# no rhyme or reason mathematically... just eyeballs.
# 218 removed because too similar to 217
acidx=( 219 183 147 153 159 158 157 193 229 223 217 )
_yap_pound ; palette=$FUNCNAME ; _idx=0
}

function yap_full_rainbow # colors
{
# this first on is the pure full rainbow
acidx=( 46 47 48 49 50 51 45 39 33 27 21 57 93 129 165 201 200 199 198 197 196 202 208 214 220 226 190 154 118 82 )

# this one adds a few more colors so that clocky.sh
acidx=( 46 47 48 49 50 51 45 39 33 27 21 56 57 63 62 93 92 129 165 201 207 206 200 199 198 197 196 202 208 214 220 226 190 154 118 82 )

_yap_pound ; palette=$FUNCNAME ; _idx=0
}


function yap_rainbow_home
{

# original bright rainbow. best on black bg.

# Fri Mar 27 09:22:26 EDT 2020
# i do not like the bright red in here: 196, 198
acidx=( 201 93 21 33 51 48 46 118 226 208 196 198 )

# softer colors slightly:
acidx=( 201 99 33 39 45 48 46 118 226 208 199 )

#         1   2   3  4  5  6  7  8  9  10  11  12  13  14
acidx=( 201 171 135 99 33 39 45 48 40 118 226 208 196 199 )
acidx=( 201 171 135 99 33 39 45 48 40 118 226 208 203 199 )
acidx=( 201 171 135 99 33 39 45 40 48 154 226 208 203 199 )
acidx=( 201 171 99 33 39 43 46 154 190 226 220 214 208 196 )
acidx=( 201 171 135 99 33 39 45 48 40 154 226 208 203 199 )
_yap_pound ; palette=$FUNCNAME ; _idx=0
}

#----------------------------------------------------------------------#
# hence, one rainbow for home, and one for work.                       #
#----------------------------------------------------------------------#
function yap_rainbow_work
{
acidx=( 201 171 99 33 39 43 46 154 190 226 220 214 208 196 )
_yap_pound ; palette=$FUNCNAME ; _idx=0
}


#----------------------------------------------------------------------#
# different screens look better with different color sets.             #
#----------------------------------------------------------------------#
function yap_rainbow_bright # colors
{
if [[ $( hostname ) == umber-hulk ]]; then
    yap_rainbow_home
else
    yap_rainbow_work
fi
}



function yap_spiral_rainbow # colors
{
acidx=(
   42 43 44 38 32 26
   25 24 30 36 37 31
   67 73 72 66 60 61
   62 68 74 80 79 78

  114 115 116 110 104 98
  97 96 102 108 109 103
  139 145 144 138 132 133
  134 140 146 152 151 150

  186 187 188 182 176 170
  169 168 174 180 181 175
  211 217 216 210 204 205
  206 212 218 224 223 222
  )
_yap_pound ; palette=$FUNCNAME ; _idx=0
}



function yap_random_colors # colors
{
#----------------------------------------------------------------------#
# give me a nice round prime numbers worth                             #
#----------------------------------------------------------------------#
acidx=( $(
num=0
while [[ $num -lt 98 ]]; do
    (( num += 1 ))
    (( r = RANDOM % 6 ))
    (( g = RANDOM % 6 ))
    (( b = RANDOM % 6 ))
    (( idx = 16 + ( r * 36 ) + ( g * 6 ) + b ))
    echo -n " $idx"
done
) )

_yap_pound ; palette=$FUNCNAME ; _idx=0
}


#----------------------------------------------------------------------#
# list of lists of colors, pegged to a descriptive function name.      #
#----------------------------------------------------------------------#
function yap_2_colors # colors
{
local r g b idx
acidx=( 231 188 ) # white grey
acidx=( 231 194 ) # white green
#----------------------------------------------------------------------#
# select random color                                                  #
#----------------------------------------------------------------------#
(( r = RANDOM % 3 + 3 ))
(( g = RANDOM % 3 + 3 ))
(( b = RANDOM % 3 + 3 ))
(( idx = (36 * r) + (6 * g) + b + 16 ))
acidx=( 231 $idx ) # white random-pastel
_yap_pound ; palette=$FUNCNAME ; _idx=0
}


function yap_pastels1 # colors
{
acidx=(
     45  49  50  51  80
     81  86  87 116 117
    121 122 123 156 157
    158 159 219 223 224
    225 229 251 252 253
    ) 
_yap_pound ; palette=$FUNCNAME ; _idx=0
}

function yap_pastels2 # colors
{
acidx=(
      44  45  50  51  80
      81  86  87 116 117
     122 123 152 153 158
     159 177 182 183 187
     188 189 193 194 195
     218 219 223 224 225
     229 230 231
     )
_yap_pound ; palette=$FUNCNAME ; _idx=0
}

function yap_pastels3 # colors
{
acidx=(
     44  45  50  51  80
     81  86  87 111 116
    117 122 123 147 152
    153 158 159 177 182
    183 187 188 189 193
    194 195 218 219 223
    224 225 229 230 231
    )
_yap_pound ; palette=$FUNCNAME ; _idx=0
}



function yap_cream # colors
{
# background needs to be set in the terminal.app options

#          B  P  R  O   G  C  G
#          L  U  E  R   R  Y  R
#          U  R  D  A   E  A  E
#          E  P   . N   E  N  Y
#           . L   . G   N   .
#           . E   . E    .  .
#

case ${1:-${HOSTNAME:-work}} in
    # dark colors incremented by . . .
    # generated by method_b

    1)
        acidx=( 17 53 52 58 22 23 ) ;;
    
    2)
        acidx=( 18 90 88 100 28 30 ) ;;

    3)
        acidx=( 19 127 124 142 34 37 ) ;;
    
    4|umber-hulk)
        acidx=( 20 164 160 184 40 44 ) ;;

    5)
        acidx=( 21 201 196 226 46 51 ) ;;

    *)
        # 1, but wrong...?
        acidx=( 17 53 52 58 22 23 59 ) ;;
esac

_yap_pound ; palette=$FUNCNAME ; _idx=0
# force foreground
_g=38
# clear any background setting
# echo "[m"
}


function yap_cream2 # colors
{
# background needs to be set in the terminal.app options

case ${HOSTNAME:-work} in
    umber-hulk) 
        # 2s
        acidx=( 19 124 )
        ;;

    *)
        # 1s
        acidx=( 17 52 )
        ;;
esac

_yap_pound ; palette=$FUNCNAME ; _idx=0
# force foreground
_g=38
# clear any background setting
# echo "m"
}


function roger # colors
{
acidx=(
    46 41 36
    27 33 31
    26 21 39
    69 63 57
    56 55 91
    92 93 99
    105 115 79
    43 
)
acidx=( 201 171 135 99 33 39 45 48 40 )
#         1   2   3   4  5  6  7  8  9 10 11 12 13  14
acidx=( 207 201 171 135 99 93 57 33 39 44 42 46 82 118 )
#----------------------------------------------------------------------#
# Sun Mar 28 17:05:22 EDT 2021                                         #
#----------------------------------------------------------------------#
acidx=( 213 201 164 129 93 57 21 27 33 39 45 43 48 46 )
_yap_pound ; palette=$FUNCNAME ; _idx=0
}


function roger2 # colors
{
#----------------------------------------------------------------------#
#     218 212 206 200 # line 2                                         #
#----------------------------------------------------------------------#
#     129 135 141 153 159 # line 5                                     #
#----------------------------------------------------------------------#
acidx=(
    201 207 213 219
    218 212     200

    164 170 176 182
    183 177 171 165

        135 141 153 159
        158 157 156 155 154
        148 149 150 151 152
    146 140 134 128

    92  98  104 110 116
        115 114 113 112
        118 119 120 121 122
    123 117 111 105 99  93

    57  63  69  75  81
        87  86  85  84  83
        82  76  77  78  79
    80  81  74  68  62  56

    20  26  32  38  44
        43  42  41  40  46
        47  48  49  50  51
    45  39  33  27  21

    57  93 129 165 ### for circular effect, some repeats.

    )
_yap_pound ; palette=$FUNCNAME ; _idx=0
}



function yap_greens3 # colors
{
acidx=()
for (( x=0; x < 10; x++ )); do
# x in 0 1 2 3 4 5 6 7 8 9 ; do
    (( r = RANDOM % 3 ))
    (( g = RANDOM % 4 + 2 ))
    (( b = RANDOM % 3 + 2 ))
    (( idx = ( r * 36 ) + ( g * 6 ) + b + 16 ))
    acidx[x]=$idx
done
_yap_pound ; palette=$FUNCNAME ; _idx=0
}


function blook # colors
# blue to cyan
{
acidx=( 17 18 19 20 21 27 33 39 45 51 87 123 159 195 )
acidx=( 195 159 123 87 51 45 39 33 27 21 20 19 18 17 )
_yap_pound ; palette=$FUNCNAME ; _idx=0
}

function bloop # colors
# blue to purple
{
# blue to purple
acidx=( 17 18 19 20 21 57 93 129 165 201 207 213 219 225 )
_yap_pound ; palette=$FUNCNAME ; _idx=0
}


function yap_gcw # colors
{
acidx=( 28 34 40 46 47 48 49 50 51 87 123 159 195 231 )
acidx=( 231 195 159 123 87 51 50 49 48 47 46 40 34 28 )
_yap_pound ; palette=$FUNCNAME ; _idx=0
}


function yap_greens # colors
{
acidx=( 230 229 228 227 226 190 154 118 82 46 40 34 28 22 )
_yap_pound ; palette=$FUNCNAME ; _idx=0
}


function yap_yellow # colors
{
acidx=( 226 220 214 208 202 196 202 208 214 220 )

# yellow on bottom, red on top
# this one looks better. not sure why.
acidx=( 52 88 124 160 196 202 208 214 220 226 227 228 229 230 )

# red on bottom, yellow on top
acidx=( 230 229 228 227 226 220 214 208 202 196 160 124 88 52 )

_yap_pound ; palette=$FUNCNAME ; _idx=0
}

function yap_blue # colors
{
acidx=( 21 27 33 39 45 )
acidx=( 20 21 27 26 32 33 38 39 45 81 75 74 68 69 63 62 )
_yap_pound ; palette=$FUNCNAME ; _idx=0
}


function yap_blues2 # colors
{
acidx=( 81  117  159  123  87  51  45 )
_yap_pound ; palette=$FUNCNAME ; _idx=0
}


function yap_burple # colors
{
# colors to go with barb palette
acidx=(
    231 225 219 213 207
    201 165 164 128 129
     93  92  57  56  57
     92  93 129 128 164
    165 201 207 213 219
    225
)
acidx=(
    225 219 213 207 201
    165 164 128 129  93
     92  57  56  57  92
    129 128 164 165 201
    207 213 219
)
_yap_pound ; palette=$FUNCNAME ; _idx=0
}


function yap_purples # colors
{
acidx=( 201 165 129 93 57 21 )
acidx=(
    127 128 129 133 134
    135 163 164 165 169
    170 171 199 200 201
    205 206 207 105 99
    93 92 98 63 57
    56 62 135 129
    )

acidx=(
    56 57 62 63 92
    93 98 99 105 141
    135 134 133 127 128
    129 165 164 163 169
    170 171 177 213 207
    206 205 199 200 201
    )

acidx=( 231 225 219 213 207 201 165 164 128 129 93 92 57 56 )
_yap_pound ; palette=$FUNCNAME ; _idx=0
}

#----------------------------------------------------------------------#
# BEGIN CURSORY METHODS                                                #
#----------------------------------------------------------------------#

function method_b
{
# generate colors in all increments.
# this was me trying to figure out
# nice looking dark colors for a
# cream colored background screen.
for x in 1 2 3 4 5 ; do

echo "# ${x}"
echo -n 'acidx=( '

while read r g b ; do

    (( r  = r * x ))
    (( g  = g * x ))
    (( b  = b * x ))

    (( idx = ( 36 * r ) + ( 6 * g ) + b + 16 ))

    echo -n "$idx "

done << EOF
0 0 1
1 0 1
1 0 0
1 1 0
0 1 0
0 1 1
EOF
echo ")"
echo

done
} # end method_b


function black_it
{
case $_g in
    (38) echo -n "[40m" ;;
    (48) echo -n "[30m" ;;
esac
}

function yap_toggle
{
yap_toggle_ground
}

function yap_toggle_ground
{
case $_g in
    (38) _g=48 ; black_it ;;
    (48) _g=38 ; black_it ;;
    # 38) _g=48 ; echo '[38;5;0m' ;;
    # 48) _g=38 ; echo '[48;5;0m' ;;
esac
}


#----------------------------------------------------------------------#
# make a palette cyclical by adding the reversed list to itself.       #
#----------------------------------------------------------------------#
function booyah # colors. not really. but just to remind me it exists.
{

local _acidx

declare -a _acidx

_acidx=( ${acidx[*]} )

acidx=( $( (
    echo ${_acidx[*]} | trr ;
    echo ${_acidx[*]} | trr | nl | sort -rn | sed -n '2,$p' | fields 2
    ) | uniq
    )
    )

_yap_pound ; palette=${palette}_booyah ; _idx=0

return
}


#----------------------------------------------------------------------#
# DEBUGGING FUNCTIONS                                                  #
#----------------------------------------------------------------------#

#----------------------------------------------------------------------#
# show me available methods.                                           #
#----------------------------------------------------------------------#
function yap_show
{
#----------------------------------------------------------------------#
# Too bad about the hard-coding. Must protect against cyclic problems. #
#----------------------------------------------------------------------#
egrep '^function(.yap|.*#.color)' $HOME/Dropbox/bin/yaps1 |
    awk '{print $2}' |
    sort -u
echo ========================================================================
echo ORDER=$_yap_order
echo PALETTE=$palette
echo ========================================================================
yap_show_colors
echo ========================================================================
}


#----------------------------------------------------------------------#
# show me current color scheme.                                        #
#----------------------------------------------------------------------#
alias yappy=yap_show_colors
alias yippy=yap_show_colors2
alias yappo='yappy ; yippy'


function yap_show_colors
{
#----------------------------------------------------------------------#
# prints a horizontal bar.                                             #
#----------------------------------------------------------------------#

pouncy white $palette
local num=0
for idx in ${acidx[*]}; do
    (( num += 1 ))
    printf "[38;5;${idx}m %3d [m" $num
done
echo
for idx in ${acidx[*]}; do
    printf "[38;5;${idx}m %3d [m" $idx
done
echo
for idx in ${acidx[*]}; do
    printf "[30m[48;5;${idx}m %3d [m" $idx
done
echo
for idx in ${acidx[*]}; do
    printf "[30m[48;5;${idx}m %3.3s [m" " "
done
echo
}


function yap_show_colors2
{
#----------------------------------------------------------------------#
# prints a vertical bar.                                               #
#----------------------------------------------------------------------#
pouncy white $palette
local num=0
for idx in ${acidx[*]}; do
    (( num += 1 ))
    printf "[38;5;${idx}m %3d [m" $num
    printf "[38;5;${idx}m %3d [m" $idx
    printf "[30m[48;5;${idx}m %3d [m" $idx
    echo -n " "
    printf "[30m[48;5;${idx}m %12.12s [m" " "
    echo
done
}


function yap_demo
{
for x in ${acidx[*]}; do
    idx=$( $_yap_order )
    echo "[${_g};5;${idx}m"
    echo $idx
    /bin/ls -l | grep -v total | head -3
done
}


#----------------------------------------------------------------------#
# DETERMINE NEXT COLOR; RANDOM OR SEQUENTIAL                           #
#----------------------------------------------------------------------#
function yap_random
{
_yap_order=_yap_random
}


function _yap_random
{
(( _idx = RANDOM % pound_acidx ))
echo ${acidx[$_idx]}
}

#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - #

function yap_sequential
{
_yap_order=_yap_sequential
}


#----------------------------------------------------------------------#
# next color index in the sequence, or rollover.                       #
# gosh. could really use a specialized Collections.counter.container   #
# for such advanced programming: loops.                                #
#----------------------------------------------------------------------#
function _yap_next
{
(( _idx += 1 ))
if [[ $_idx -ge $pound_acidx ]]; then
    _idx=0
fi
}


function stars
{
local lines=$LINES columns=$COLUMNS
local objects a y x bg_idx fg_idx

declare -a objects

objects=( ★ ☆ ✦ ✧ ✩ ✫ ✬ ✭ ✮ ✯ ✰ ✴ ✵ ✶ ✷ ✸ ✹ )

for a in ${objects[*]} ; do

    (( y = RANDOM % lines ))
    (( x = RANDOM % columns ))
    # tput cup $y $x
    (( bg_idx = ( RANDOM % ( 6 * 36 ) ) + 16 ))
    pouncy -n $bg_idx $bg_idx
    # (( fg_idx = ( RANDOM % ( 6 * 36 ) ) + 16 ))
    # pouncy -n $bg_idx,$fg_idx $a
done
(( lines -= 1 ))
tput cup $lines 0
}


function _yap_sequential
{
. $FPS1
_yap_next
echo _idx=$_idx > $FPS1
echo ${acidx[$_idx]}
}



#----------------------------------------------------------------------#
# MAIN                                                                 #
#----------------------------------------------------------------------#

#----------------------------------------------------------------------#
# change the command prompt, PS1, to cycle through background colors.  #
#----------------------------------------------------------------------#
#----------------------------------------------------------------------#
# HOSTNAME=$( hostname )                                               #
#----------------------------------------------------------------------#
#----------------------------------------------------------------------#
# case $HOSTNAME in                                                    #
#     (umber-hulk) ;;                                                  #
#     (*) HOSTNAME='salp-shark' ;;                                     #
# esac                                                                 #
#----------------------------------------------------------------------#

# Useful: 
# 
# \!     the history number of this command 
# \e     an ASCII escape character (033) 
# 
# Useful, not used: 
#    
# \j    the number of jobs currently managed by the shell 
# \n    newline 
# 
# \r    carriage return 
# \s    the name of the shell, the basename of $0 (the portion following the final slash) 
# 
#   
# \D{format} the format is passed to strftime(3) and the 
#       result is inserted into the prompt  string;  an  empty format 
#       results in a locale-specific time representation.
#       The braces are required 
# 
# \d    the date in "Weekday Month Date" format (e.g., "Tue May 26") 
# 
# \w    the current working directory, with $HOME abbreviated with a tilde 
# 
# \t    the current time in 24-hour HH:MM:SS format 
# \T    the current time in 12-hour HH:MM:SS format 
# \@    the current time in 12-hour am/pm format 
# \A    the current time in 24-hour HH:MM format 
# 
# \\    a backslash 
# \#    the command number of this command ??? 
# 
# \u    the username of the current user 
# \v    the version of bash (e.g., 2.00) 
# \V    the release of bash, version + patch level (e.g., 2.00.0) 
# \W    the basename of the current working directory, with $HOME abbreviated with a tilde 
# \nnn  the character corresponding to the octal number nnn 
# 
# # this was used in the ubuntu prompt to set the terminal title. 
# # see exec: `title` for a bash implementation. 
# 
# \[    begin a sequence of non-printing characters,
        which could be used to embed a terminal control sequence into the prompt 
# \]    end a sequence of non-printing characters 
# 
# Not Useful:
# 
# \$    if the effective UID is 0, a #, otherwise a $ 
# \a    an ASCII bell character (07) 
# \l    the basename of the shells terminal device name 
# 
#----------------------------------------------------------------------


function yap_on
{
export YAP=on
#----------------------------------------------------------------------#
# export PS1='[${_g};5;`$_yap_order`m${HOSTNAME}✴ • ✭ . ✦ °\!. ✴ ° ✭ • ✦ -> ' #
# export PS1='[${_g};5;`$_yap_order`m${HOSTNAME} \! -> [m '          #
# export PS1='[${_g};5;`$_yap_order`m${HOSTNAME} ✴✭✦•- \! -•✦✭✴ -> ' #
# export PS1='[${_g};5;`$_yap_order`m${HOSTNAME} ✶✭✦▲ \! ▲✦✭✶ -> ' #
# export PS1='[${_g};5;`$_yap_order`m${HOSTNAME} ✶✭✦ \! ✦✭✶ -> ' #
#----------------------------------------------------------------------#
export PS1='------------------------------------------------------------------------\n\@ \# \n\h ✶✭✦ \! ✦✭✶ \$ [${_g};5;`$_yap_order`m'

}


function yap_off
{
export YAP=off
export PS1='${HOSTNAME} \! -> '
export PS1='${HOSTNAME} ${PWD} `date "+%Y-%m-%d %H:%M:%S"` \! -> '
export PS1='${HOSTNAME} ✴ ✭ ✦ .•°\!°•✴ ✭ ✦. -> '
export PS1='${HOSTNAME} ✴✴✭✦.•°\!°•✴✴✭✦. -> '
echo
}


# convert a comma or space separated list into an instant color-idx-list
function sling
{
#----------------------------------------------------------------------#
# acidx=( $(                                                           #
#     echo $* | tr , ' '                                               #
#     ) )                                                              #
#----------------------------------------------------------------------#
acidx=(${*//,/ })
_yap_pound ; palette=$FUNCNAME ; _idx=0
echo
yippy
echo
yappy
}


function grab_palettes
{
palettes=$(
grep '^function.* \# color' $HOME/Dropbox/bin/yaps1 |
    awk '{print $2}' |
    sort -u
    )
}


function yap_palettes
{
local num anum

palettes=$( 
    grep '^function.* \# color' $HOME/Dropbox/bin/yaps1 |
        awk '{print $2}' |
        sort -u
    )
#----------------------------------------------------------------------#
# this was a nightmare. hard-coding is fine.                           #
#----------------------------------------------------------------------#
for palette in ${palettes[*]} ; do
    pouncy white $palette
    eval $palette
    num=0
    anum=0
    while [[ $num -lt $pound_acidx ]]; do
        printf "[48;5;${acidx[$num]};30m%3d [m" ${acidx[$num]}
        (( num += 1 ))
        (( anum += 1 ))
        if [[ $anum -ge 14 ]]; then
            echo "[m"
            anum=0
        fi
    done
#----------------------------------------------------------------------#
# double-space between palettes                                        #
#----------------------------------------------------------------------#
    if [[ $anum != 0 ]]; then
         echo "[m"
    fi
    echo
done
return
}


# MAIN

_idx=0

#----------------------------------------------------------------------#
# set default color ordering.                                          #
# last entry wins.                                                     #
#----------------------------------------------------------------------#
_yap_order=_yap_random
_yap_order=_yap_sequential

#----------------------------------------------------------------------#
# set default color scheme.                                            #
# last entry wins.                                                     #
#----------------------------------------------------------------------#
#----------------------------------------------------------------------#
# default foreground/background indicator to background                #
# param >>> previous-setting >>> default-value                         #
#----------------------------------------------------------------------#
case ${1:-${_g:-fg}} in # default: foreground
    (back*|bg|48) _g=48 ; black_it ;;
    (fore*|fg|38) _g=38 ; black_it ;;
    (cream) _g=38 ; yap_cream ;;
    *) _g=${_g:-48} ;; # fall-through, use background
esac

#----------------------------------------------------------------------#
# finally... set the new PS1 environ.                                  #
#----------------------------------------------------------------------#
yap_rainbow_bright
yap_on

